apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vapz6eawz-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vapz6eawz-java-quarkus-gitops